-- Per-agent notifications, surfaced by the header bell.
--
-- The header needed a badge count and a list of notices that survive a page
-- load, so this is a real table rather than anything client-side. Notices are
-- generated by a trigger on the agent order tables, which means an order
-- moving to a terminal state raises a notice without any application code
-- having to remember to do it - the same reasoning as the activity log.
--
-- Read and update access is granted through RLS against auth.uid() only. There
-- is deliberately no edge function here: a service-role function would be able
-- to read and mark other agents' notices, and the browser client with RLS
-- cannot. Fewer moving parts and a smaller blast radius.

create table if not exists public.notifications (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text,
  -- Drives the icon and colour in the dropdown. A closed set so the frontend
  -- never has to guess how to render an unknown kind.
  kind text not null default 'info'
    check (kind in ('info', 'success', 'warning', 'error')),
  -- Which order the notice is about, so the dropdown can deep-link and so one
  -- transition cannot raise the same notice twice.
  order_table text,
  order_id text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_idx
  on public.notifications(user_id, created_at desc);

-- At most one unread notice per (agent, order, title). A status sync that runs
-- repeatedly must not fill the bell with duplicates.
create unique index if not exists notifications_dedupe_idx
  on public.notifications(
    user_id,
    coalesce(order_table, ''),
    coalesce(order_id, ''),
    title
  )
  where read_at is null;

-- ---------------------------------------------------------------------------
-- Notices from order status changes
-- ---------------------------------------------------------------------------
-- The two agent order tables do not agree on their column names: data orders
-- carry `status`, airtime orders carry `airtime_status`, and airtime orders
-- name the owner `user_id` where data orders use `agent_id`. The row is read
-- through to_jsonb() so one function covers both, and so attaching it to a
-- third table later cannot fail on a missing field.
--
-- Only terminal transitions raise a notice. 'processing' is the normal path
-- for a fresh order and does not deserve a notification, and 'pending_payment'
-- is the pre-payment window.

create or replace function public.notify_agent_of_order_status()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new jsonb := to_jsonb(new);
  v_old jsonb := to_jsonb(old);
  v_table text := tg_table_name;
  v_status_col text;
  v_new_status text;
  v_old_status text;
  v_user uuid;
  v_title text;
  v_kind text;
  v_ref text;
begin
  -- Pick whichever status column this table actually has.
  v_status_col := case
    when v_new ? 'status' then 'status'
    when v_new ? 'airtime_status' then 'airtime_status'
    else null
  end;
  if v_status_col is null then
    return new;
  end if;

  v_new_status := v_new ->> v_status_col;
  v_old_status := v_old ->> v_status_col;

  if v_new_status is not distinct from v_old_status then
    return new;
  end if;

  if v_new_status = 'successful' then
    v_title := 'Order delivered';
    v_kind := 'success';
  elsif v_new_status = 'failed' then
    v_title := 'Order failed - wallet refunded';
    v_kind := 'error';
  elsif v_new_status = 'cancelled' then
    v_title := 'Order cancelled';
    v_kind := 'warning';
  else
    -- 'processing', 'pending', 'pending_payment' and anything new: not worth
    -- a notice.
    return new;
  end if;

  -- The owning agent, whichever column this table keeps them in.
  v_user := nullif(coalesce(v_new ->> 'agent_id', v_new ->> 'user_id'), '')::uuid;
  if v_user is null then
    return new;
  end if;

  v_ref := coalesce(
    v_new ->> 'short_code',
    v_new ->> 'provider_reference',
    v_new ->> 'payment_reference'
  );

  insert into public.notifications (user_id, title, body, kind, order_table, order_id)
  values (
    v_user,
    v_title,
    case
      when v_ref is not null then 'Order ' || v_ref
      else 'Your order is now ' || replace(v_new_status, '_', ' ')
    end,
    v_kind,
    v_table,
    v_new ->> 'id'
  )
  on conflict do nothing;

  return new;
exception
  when others then
    -- A notification must never block the status change that caused it, and
    -- must never surface as an error to the caller settling an order.
    return new;
end
$$;

drop trigger if exists notify_agent_data_orders on public.agent_data_orders;
create trigger notify_agent_data_orders
  after update of status on public.agent_data_orders
  for each row execute function public.notify_agent_of_order_status();

drop trigger if exists notify_agent_airtime_orders on public.airtime_orders;
create trigger notify_agent_airtime_orders
  after update of airtime_status on public.airtime_orders
  for each row execute function public.notify_agent_of_order_status();

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.notifications enable row level security;

-- Dropped and recreated rather than patched, so a rerun cannot leave two
-- permissive policies on the same table.
drop policy if exists "Agents read their own notifications" on public.notifications;
create policy "Agents read their own notifications"
  on public.notifications for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- 'Mark all as read' is a single update of every unread row, so the policy has
-- to cover all of the agent's own rows and nothing else.
drop policy if exists "Agents mark their own notifications read" on public.notifications;
create policy "Agents mark their own notifications read"
  on public.notifications for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- No insert or delete policy: notices are written by the trigger, which runs as
-- the table owner, and history is never removed by the client. An agent can
-- read and dismiss, not fabricate or delete.
